baseURL = "http://kodofish.github.io"
title = "Kodofish"
# for smart copyright line, leave this blank and check [params.copyright]
author = "Steve Francia"
copyright = "Copyright © 2019, all rights reserved."
canonifyurls = true
theme = "silhouette-hugo"
disqusShortname = ""
googleAnalytics = ""
Paginate = 5
preserveTaxonomyNames = true
enableRobotsTXT = true # generate robots.txt

# Syntax Highlighting ( https://gohugo.io/content-management/syntax-highlighting/ )
pygmentsCodefences = true
enableEmoji = true
# Missing translations will default to this content language
defaultContentLanguage = "en"

[params]
author = "Kodofish"
introDescription = "Hi, I'm Steve Francia. Author, Speaker, Developer, Creator of Hugo, Cobra and spf13-vim. Former Docker and MongoDB."
contentSharing = "I'm happy for you to share content on this site, but please provide attribution."

[social]
instagram = "kodofish"
linkedin = "kodofish"
twitter = "kodofish"
facebook = "kodofish"

