name: github pages

on:
  push:
    branches:
    - code

jobs:
  build-deploy:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: true


    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: '0.67.0'
        # extended: true

    - name: Build Hugo
      run: hugo --minify

    - name: Deploy Hugo
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.ACTIONS_DEPLOY_KEY}}
        PUBLISH_BRANCH: master
        PUBLISH_DIR: ./public
        cname: kodofish.dev
        commit_message: ${{ github.event.head_commit.message }}
        
    - uses: actions/checkout@v2
    - name: Slack Notification
      uses: rtCamp/action-slack-notify@v2.0.1
      env:
        SLACK_USERNAME: Github Action
        SLACK_ICON: https://github.githubassets.com/images/modules/logos_page/Octocat.png
        SLACK_TITLE: kodofish.dev deploy done.
        SLACK_MESSAGE: 'kodofish.dev deploy success :rocket:'
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
