name: github pages

on:
  push:
    branches:
    - code

jobs:
  build-deploy:
    runs-on: ubuntu-18.04
    steps:
    - name: Checkout Submodules
      uses: actions/checkout@v1
      # 如果使用了git submodules
       with:
         submodules: true

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: '0.67.0'
        # extended: true

    - name: Build Hugo
      run: hugo --minify

    - name: Deploy Hugo
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.ACTIONS_DEPLOY_KEY}}
        PUBLISH_BRANCH: master
        PUBLISH_DIR: ./public
        cname: kodofish.dev
        commit_message: ${{ github.event.head_commit.message }}
