name: github pages

on:
  push:
    branches:
    # 你的hugo源码分支
    - code

jobs:
  build-deploy:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1
      # 如果使用了git submodules
      # with:
      #   submodules: true

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: '0.59.1'
        # extended: true

    - name: Build
      run: hugo --minify

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      env:
        github_token: ${{ secrets.ACTIONS_DEPLOY_KEY}}
        # 你的github page分支
        PUBLISH_BRANCH: master
        PUBLISH_DIR: ./
